name: Build base python docker images
run-name: ${{ github.actor }}
on: [ push ]
env:
  REGISTRY: registry.gitlab.com/ronen48/ciy
  GOPATH: "."
jobs:
  build-docker-image-and-push:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to gitlab hub
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com/ronen48/ciy
          username: ronen
          password: glpat-MUekjoxQDubT9QoHyuEx
      - name: Run build
        run: chmod +x ./hack/build-images.sh && make local-image

      - name: Push docker image
        run: |
          docker push registry.gitlab.com/ronen48/ciy/kube-scheduler:latest