name: Build base python docker images
run-name: ${{ github.actor }}
on: [ push ]
env:
  REGISTRY: registry.gitlab.com/ronen48/ciy
jobs:
  build-docker-image-and-push:
    runs-on: [self-hosted, linux]
    env:
      GOMODCACHE: /tmp/gomodcache
      GOCACHE: /tmp/gocache
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run build
        env:
          GOPATH: ${{ github.workspace }}
        run: chmod +x ./hack/build-images.sh && make build-scheduler.amd64

      - name: Release arm64 package
        run: |
          PACKAGE_VERSION=1.0.0
          PACKAGE_REGISTRY_URL="https://gitlab.com/api/v4/projects/54080196/packages/generic/ciy-scheduler/$PACKAGE_VERSION"
          curl --header "PRIVATE-TOKEN: glpat-3zqVQwKxwU_Qsvc_8fw8" --upload-file ./bin/kube-scheduler $PACKAGE_REGISTRY_URL/kube-scheduler.bin